### PR TITLE
Added group template setting to Importer Rules.

### PR DESCRIPTION
**Pull request by K-Dark**
This allows the user to select from the available group templates.
All found assets will apply the template's settings to new or already existing groups.

This does not change the default behavior, it only adds some customization options to the rules.

Not sure if that interests you but we needed this for our project!

### CODE REVIEW

**Comment by favoyang** [comment]
Hi @K-Dark, thanks for the contributions. It looks a good PR. Do you think the behaviour should be limited to only when the importer created a new group (with `allowGroupCreation=True`). Otherwise, each time a rule matched with an asset path, the group template gonna be applied once.

**Comment by K-Dark** [comment]
I let it reapply the settings even if the group was already created in case something changes during development (which was precisely my case).
That allowed me to update all existing groups, and handle automatically future groups that may be created later on!

**Comment by favoyang** [comment]
I understand it may totally make sense in your case, however not for all others.
- The word "template" hints it be applied once, then can be customized later. I checked the source code, it only used for creating a new group.
image
- The PR changed a group settings to *read only*, but a developer still be able to edit a group manually. Then the changes will be override next time a rule applied. It's not very friendly.
- It may also introduce performance issue for larger project.

I think the best way to achieve what you described, is to write a constraint script to sync a template to target group before a content build. Or even better Addressables can introduce a group type called "ReferenceGroup/ProxyGroup", which proxies all settings to another group / template.

So I would be happy to merge, if the template only applied to new created group. Feel free to correct me or you may have a better point.

**Comment by K-Dark** [comment]
Hmm, you make a good point.

- I agree that both uses could have their uses. If it only applies on group creation, the user is responsible for updating groups as time goes. If it always applies, the system is automated, and user input is discarded. What do you think about giving the end user the choice then? I can add a check box to choose between the two modes.

- The group settings would then only be read only if the user chooses to overwrite them in the rule settings.

-  After profiling a bit I wouldn't be too worried about performance issues. A call to ApplyToAddressableAssetGroup costs 10ms (in deepProfile mode). That would be one second for 100 groups with custom templates. That doesn't sound too bad. For comparison, during my test I used "CheckFolders" on one folder containing 20 assets, the whole importer took about 4 seconds (still deep profile mode).
image

It's your decision in the end and I will of course respect it.

**Comment by favoyang** [comment]
Thanks for the profiling. A rule settings sounds not bad for me.

**Comment by K-Dark** [comment]
PR updated with new setting. Have a great week-end!

**Comment by favoyang** [comment]
Thanks for the update, and have a nice weekend!

**Pull request merged**
