### PR TITLE
Improve the inspector for AddressableImportSettings

### PR DESCRIPTION
**Pull request by laicasaane**
Fix issue https://github.com/favoyang/unity-addressable-importer/issues/59
- [x] Change the order of rule properties a bit
- [x] Add `[Space]` before the list of rules
- [x] Use `OdinAttributeProcessor` to add attributes to the properties
- [x] Add a custom colored foldout group

image

image

### CODE REVIEW

**Comment by favoyang** [comment]
@laicasaane just request me when it's ready to review.

Notice that it should work with or without ODIN.

image

**Comment by laicasaane** [comment]
@favoyang Strange, I cannot add you as a reviewer. Hmm.

> Notice that it should work with or without ODIN.

Yes, it works even without Odin.

**Comment by laicasaane** [comment]
@favoyang Well, I give up, don't know why I can't assign you. But this PR is ready to be reviewed.

**Comment by favoyang** [comment]
@laicasaane weird. I will review your code later this week.

**Comment by laicasaane** [comment]
Oh. Now I understand the actual behaviour of `Group Name` field, using it as the rule's name may not be appropriate.

**Comment by laicasaane** [comment]
Maybe I should remove the sections grouping those fields. They now seem redundant to me, and make it hard to realize the relationship between `Path` and the 2 fields `Group Name` and `Address Replacement`.

**Comment by favoyang** [comment]
image
I didn't see those sections that group fields, is that ODIN only? Tested 9dd4121f1610fac3e8cde77e0e53e25e21f63a9c with Unity 2021.2.4f1, Addressables@1.2.4

> Oh. Now I understand the actual behaviour of `Group Name` field, using it as the rule's name may not be appropriate.

I think using the `path` as the rule's name is more appropriate.


> Maybe I should remove the sections grouping those fields. They now seem redundant to me, and make it hard to realize the relationship between `Path` and the 2 fields `Group Name` and `Address Replacement`.

I suggest using vertical spacings to make it look visually grouped and less redundant. The first field of each "group" implies the group function.

```
Path ______
[v] Match Type

Group Name ______
Group Template ______
[v] Group Template Application Mode

[>] Labels
[>] Dynamic Labels
[v] Label Mode

[v] Address Simplified
Address Replacement ______ # Hide then Match Type is wildcard.
```

It describes as, "please put matched paths into the given group, add some labels and perhaps make a change of the imported addresses."

**Comment by laicasaane** [comment]
> I didn't see those sections that group fields, is that ODIN only?

Yes, I was making this UI for Odin only.

> I think using the `path` as the rule's name is more appropriate.

I think so too.

> Haven't reviewed the code yet

It's OK. I just need some time to rework this PR, and, maybe, make a custom editor using UIToolkit too. I will put your feedback into test later this week.

**Comment by laicasaane** [comment]
@favoyang I've implemented your suggestion and add some supports for native inspector without Odin.

**Comment by favoyang** [comment]
@laicasaane 

I'm not sure if the intents before Match Type and Application Mode are necessary, it didn't feel very consistent. Maybe it's a misunderstanding, I'm using the `[v]` as a mark for drop-down select (I probably should put it at the end of a line), and `[>]` as collapse-able content.

```
Path ______
Match Type [v] 

Group Name ______
Group Template ______
Group Template Application Mode [v] 

[>] Labels
[>] Dynamic Labels
Label Mode [v]

Address Simplified [v] 
Address Replacement ______ # Hide when the Match Type is wildcard.
```

Without the intent, it looks ok to me.

image

BTW, I synced the PR branch with the latest master.

**Comment by laicasaane** [comment]
> Maybe it's a misunderstanding

Probably a misunderstanding. I'll remove the indents.

**Comment by favoyang** [comment]
> Btw, shouldn't this be a checkbox rather than a dropdown?

Sorry, my bad.

```
[x] Address Simplified
```

**Comment by laicasaane** [comment]
Hi @favoyang, I've removed the unnecessary indentation. Please review and merge this PR if possible.

image

**Review by favoyang — APPROVED** [review]
Looks good!

**Pull request merged**
