### PR TITLE
feat: dynamic labels (close: #47)

### PR DESCRIPTION
**Pull request by gtoto007**
I have added the support to create dynamic labels when an addressable asset is added automatically in an addressable group.

You can to watch a video demo:
https://youtu.be/r5bCKY6TvP0

Support for static labels has been maintained to ensure backward compatibility

TL;DR
- Open Addressable Import Settings file
- Add  your dynamic label  in field "Dynamic Labels". You can use the same naming convention of group replacement (i.e rules regex)
- If the dynamic label does not exist, it will be create.
- The dynamic label will be added to the addressable asset

To avoid having dirty commits due to the automatic code alignment, I isolated the reformat code  in the first commit using the auto detection system of the IDE Rider

### CODE REVIEW

**Comment by favoyang** [comment]
@gtoto007 thank you for the contribution. Based on my schedule it gonna take a while for time to process this.

**Comment by favoyang** [comment]
Hi @gtoto007,

Thanks for the PR and the instruction video. Could fix the ODIN support?
```
--- a/Editor/OdinSupport/AddressableImporterFilterOdinHandler.cs
+++ b/Editor/OdinSupport/AddressableImporterFilterOdinHandler.cs
@@ -100,7 +100,7 @@

         private bool ValidateLabelsPath(AddressableImportRule rule, string filter)
         {
-            return rule.labels.Any(x => x.IndexOf(filter, StringComparison.OrdinalIgnoreCase) >= 0);
+            return rule.labelsRefsEnum.Any(x => x.IndexOf(filter, StringComparison.OrdinalIgnoreCase) >= 0);
         }

         private void FilterRules(string filter)
```

**Comment by favoyang** [comment]
Please also rebase the master, some bug fixes was added.

**Comment by favoyang** [comment]
BTW, I did some rough tests (haven't reviewed the code yet), it feels good.

**Comment by gtoto007** [comment]
@favoyang I done! can you check?

**Review by favoyang — APPROVED** [review]
LGTM

**Pull request merged**
